package io.jpress.model;

import io.jpress.model.base.BaseCouponUsed;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="coupon_used",primaryKey="id")
public class CouponUsed extends BaseCouponUsed<CouponUsed> {

    private static final long serialVersionUID = -3409811294519884621L;
	
}
