package io.jpress.model;

import io.jpress.model.core.Table;
import io.jpress.model.base.BaseRefund;

/**
 * Generated by JPress.
 */
@Table(tableName="refund",primaryKey="id")
public class Refund extends BaseRefund<Refund> {
	
}
